// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7mPuIL164YZF9Sqam3g-60dKLs3FujNw',
    appId: '1:99343113914:web:410924faa8d636f86c6c83',
    messagingSenderId: '99343113914',
    projectId: 'squid-41a4f',
    authDomain: 'squid-41a4f.firebaseapp.com',
    storageBucket: 'squid-41a4f.appspot.com',
    measurementId: 'G-HXP3G7KXEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL45GTdH60UcZGIC9pO4KKlMtw01FFTBI',
    appId: '1:99343113914:android:79ee111fe17fc3cf6c6c83',
    messagingSenderId: '99343113914',
    projectId: 'squid-41a4f',
    storageBucket: 'squid-41a4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhURRm_0JYEizZdb6wk7zhLJ-fYc6-kg',
    appId: '1:99343113914:ios:d14f9407fcdbbc846c6c83',
    messagingSenderId: '99343113914',
    projectId: 'squid-41a4f',
    storageBucket: 'squid-41a4f.appspot.com',
    androidClientId: '99343113914-frqehl2iqei367ui2cnuqo4rhpbfdrps.apps.googleusercontent.com',
    iosClientId: '99343113914-16k8sv3eqfdfani6vem3ptrsnsctf8sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.squidgame',
  );
}
